[font]
size = 12.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 0 }

[window]
opacity = 0.9
dimensions = { columns = 150, lines = 45 }
